/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autonoma.demorobot.gui;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Maria Paz Puerta
 */
public class Robot extends javax.swing.JFrame {

    /**
     * Creates new form Robot
     */
    public Robot() {
        initComponents();
        this.setSize(419, 385);
        this.setLocationRelativeTo(null);
    }
    
    @Override
    public void paint(Graphics g){
        
        g.setColor(Color.GRAY); // Cabeza
        g.fillRect(150, 50, 100, 100);
        
        g.setColor(Color.BLACK);
        g.fillRect(197, 20, 6, 30); // Un rectángulo pequeño para la antena (más gruesa)
        g.fillRect(195, 10, 10, 10); // Parte de arriba de la antena (la bolita, ahora también un cuadrado si quieres)
        
        g.setColor(Color.WHITE); // Ojo 1
        g.fillOval(170, 70, 20, 20);
        
        g.setColor(Color.WHITE); // Ojo 2
        g.fillOval(210, 70, 20, 20);
        
        g.setColor(Color.BLACK); // Boca
        g.fillRect(175, 100, 50, 30);
        
        g.setColor(Color.BLACK); // Subojo 1
        g.fillOval(212, 72, 15, 15);
        
        g.setColor(Color.BLACK); // Subojo 2
        g.fillOval(172, 72, 15, 15);
        
        g.setColor(Color.GRAY); // Cuerpo
        g.fillRect(140, 160, 120, 150);
        
        g.setColor(Color.BLACK); // Brazo 1
        g.drawLine(140, 180, 100, 200);
        
        g.setColor(Color.BLACK); // Brazo 2
        g.drawLine(260, 180, 300, 200);
        
        g.setColor(Color.GRAY); // Brazo 1
        g.fillRect(100, 170, 40, 20); // Un brazo rectangular, horizontal

        g.setColor(Color.GRAY); // Brazo 2
        g.fillRect(260, 170, 40, 20); // Otro brazo rectangular, horizontal
        
        g.setColor(Color.GRAY); // Pierna 1
        g.fillRect(160, 310, 20, 50);
        
        g.setColor(Color.BLUE);
        g.fillRect(155, 360, 30, 10); // Un zapato un poquito más ancho que la pierna
        
        g.setColor(Color.GRAY); // Pierna 2
        g.fillRect(220, 310, 20, 50);
        
        // Zapato 2
        g.setColor(Color.BLUE);
        g.fillRect(215, 360, 30, 10); // Segundo zapato
        
    }

// draw line
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Robot robot = new Robot();
        robot.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
